[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0.59"
resp = "1.0.3"
tokio = { version = "1.47.1", features = ["full"] }
indexmap = "2.12.0"
clap = { version = "4.5.50", features = ["derive"] }
rand = "0.10.2"
rand_distr = "0.6.0"
base64 = "0.23.1"
log = "0.4.28"
ordered-float = { version = "4.6.0", default-features = false }
futures = "0.3.31"
sha2 = "0.10"
dashmap = "6"
bitvec = "1"
